---
- name: Tap homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items:
    - sanemat/font

- name: Install homebrew packages required xquartz
  homebrew: name={{ item.name }} install_options={{ item.options|default() }}
  with_items:
    - { name: 'ricty', options: ['vim-powerline', 'powerline'] }

- name: check ricty version
  shell: brew info ricty | grep "ricty:" | awk '{print $3;}'
  register: ricty_version

- name: copy ricty font files
  copy: src={{ item }} dest=~/Library/Fonts/ force=yes
  with_fileglob:
    - /usr/local/Cellar/ricty/{{ ricty_version.stdout }}/share/fonts/Ricty*.ttf

- name: update font cache
  shell: fc-cache -vf
  tags:
    - font-update
