---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: osx-defaults, tags: [osx-defaults]}
    - { role: brew, tags: [brew]}
    - { role: dotfiles, tags: [dotfiles]}
  vars:
    local_dotfiles_ripository: ''
