#!/bin/bash

TAG_OPT=""

usage_exit() {
        echo "Usage: provision [-t tag]" 1>&2
        exit 1
}

while getopts t:h OPT
do
    case $OPT in
        i)  INVENTORY=$OPTARG
            ;;
        t)  TAG_OPT=" -t $OPTARG"
            ;;
        h)  usage_exit
            ;;
        \?) usage_exit
            ;;
    esac
done

HOMEBREW_CASK_OPTS="--appdir=/Applications"
#echo $HOMEBREW_CASK_OPTS
ansible-playbook local.yml -vv$TAG_OPT
