---
- name: Add homebrew tap repos
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - homebrew/cask
    - homebrew/cask-versions

- name: Install/Upgrade Homebrew Cask packages
  homebrew_cask:
    name: '{{ item.name | default(item) }}'
    state: "{{ item.state | default('present') }}"
    update_homebrew: yes # requires version 2.2.0 or later
  with_items: '{{ homebrew_cask_packages }}'
  when: '{{ homebrew_cask_packages }}'
