---
- name: Checkout my dotfiles
  git:
    repo: https://github.com/aehata/dotfiles.git
    dest: ~/.dotfiles
    recursive: yes
  tags:
    - dotfiles
    - mydotfiles

- name: Create my dotfiles symlinks
  file:
    src: ~/.dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .bash_profile
    - .config
    - .gitconfig
    - .gemrc
    - .zsh
    - .zshrc
    - .zpreztorc
    - .vimrc
  tags:
    - dotfiles
    - mydotfiles

- name: Checkout anyenv
  git:
    repo: https://github.com/riywo/anyenv
    dest: ~/.anyenv
  tags:
    - dotfiles
    - anyenv

- name: Prepare anyenv-update
  command: mkdir -p ~/.anyenv/plugins
  tags:
    - dotfiles
    - anyenv

- name: Checkout anyenv-update
  git:
    repo: https://github.com/znz/anyenv-update
    dest: ~/.anyenv/plugins/anyenv-update
  tags:
    - dotfiles
    - anyenv

- name: Install pyenv
  command: anyenv install pyenv --skip-existing
  tags:
    - dotfiles
    - anyenv

- name: Checkout pyenv-virtualenv
  git:
    repo: https://github.com/yyuu/pyenv-virtualenv
    dest: ~/.anyenv/envs/pyenv/plugins/pyenv-virtualenv
  tags:
    - dotfiles
    - anyenv

- name: Checkout prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto
    dest: ~/.zprezto
  tags:
    - dotfiles
    - prezto

- name: Create prezto symlinks
  file:
    src: ~/.zprezto/runcoms/{{ item }}
    dest: ~/.{{ item }}
    state: link
    force: yes
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
  tags:
    - dotfiles
    - prezto

