---
- name: Tap homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items:
    - sanemat/font
  tags:
    - font
    - ricty

- name: Install homebrew packages required xquartz
  homebrew: name={{ item.name }} install_options={{ item.options|default() }}
  with_items:
    - { name: 'ricty', options: ['vim-powerline', 'powerline'] }
  tags:
    - font
    - ricty

- name: copy ricty font files
  copy: src={{ item }} dest=~/Library/Fonts/ force=yes
  with_fileglob:
    - /usr/local/opt/ricty/share/fonts/Ricty*.ttf
  tags:
    - font
    - ricty

- name: download cica font
  get_url:
    url: https://github.com/miiton/Cica/releases/download/v2.1.0/Cica_v2.1.0.zip
    dest: /tmp/cica.zip
    mode: 0440
  tags:
    - font
    - cica

- name: unarchive cica font
  command: unzip /tmp/cica.zip -d /tmp
  tags:
    - font
    - cica

- name: copy cica font files
  copy: src={{ item }} dest=~/Library/Fonts/ force=yes
  with_fileglob:
    - /tmp/Cica*.ttf
  tags:
    - font
    - cica

- name: update font cache
  shell: fc-cache -vf
  tags:
    - font
    - ricty
    - cica
