---
# Tap external Homebrew Cask repositories.
homebrew_cask_repositories:
  - caskroom/versions

# Managed Homebrew Cask packages.
#
# e.g.
# - package_name
# or
# { name: package_name, state: package_state }
#
# state choices: [present, absent, installed, uninstalled] (default: present)
homebrew_cask_packages:
  - alfred
  - adobe-acrobat-reader
  - airmail-beta
  - android-file-transfer
  - appcleaner
  - atom
  - box-sync
  - cheatsheet
  - cmd-eikana
  - cyberduck
  - dash
  - docker
  - dropbox
  - evernote
  - firefox
  - flash-player
  - google-chrome
  - google-drive
  - google-japanese-ime
  - iterm2
  - java
  - kindle
  - kitematic
  - ngrok
  - slack
  - sourcetree
  - the-unarchiver
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - xquartz
  - zoomus
