---
homebrew_packages:
  - aacgain
  - asciinema
  - autoconf
  - automake
  - awscli
  - certbot
  - circleci
  - direnv
  - ffmpeg
  - fzy
  - {name: fontforge, install_options: [use-gcc, without-python]}
  - gdal
  - gibo
  - {name: git, install_options: [with-brewed-curl, with-brewed-openssl]}
  - gitup
  - git-crypt
  - git-flow-avh
  - git-secrets
  - gnupg2
  - go
  - graphviz
  - hugo
  - jq
  - lua
  - mas
  - nkf
  - openvpn
  - packer
  - pandoc
  - pipenv
  - plantuml
  - reattach-to-user-namespace
  - tig
  - terraform
  - terragrunt
  - tmux
  - tree
  - {name: vim, install_options: [with-lua, override-system-vim]}
  - wget
  - yarn
  - zplug
  - zsh
